### ISSUE TITLE
A question for the baseline paper

### ISSUE THREAD

**Issue by jundengdeng** [knowledgetechnologyuhh/OMGEmotionChallenge#2]
Which data (test or validation) was used to produce the baseline results in the paper? Thanks!

**Comment by ZhangXiao96** [comment]
hello, could you please tell me where is the paper of the baseline?

**Comment by pablovin** [comment]
We will provide the baseline very soon (end of this week, beginning of the next one), and will inform you all via email as soon as we have it.
