### ISSUE TITLE
A Problem In caculateEvalutionCCC.py

### ISSUE THREAD

**Issue by ZhangXiao96** [knowledgetechnologyuhh/OMGEmotionChallenge#3]
I think there is a mistake in line 82 and line 83 of caculateEvalutionCCC.py

`                   cccArousal.append(ccc(validationArousal,modelArousal))
                    cccValence.append(ccc(validationArousal, modelArousal))`

**Comment by pablovin** [comment]
Thanks for reporting that! We just updated it.
